### PR TITLE
list avds not working in high sdk

### PR DESCRIPTION
**Pull request by truongngoclinh**
Fix issue: https://github.com/selendroid/selendroid/issues/1107
Incompatible with SDK Tools 25, command "list avds" does not exist

### CODE REVIEW

**Comment by dmitrikudrenko** [comment]
Could you upload corrected jar?

**Comment by KevinOfNeu** [comment]
new jar file should be uploaded to official site.

**Comment by rgoerner** [comment]
Does anyone know when this will be fixed :( ?

**Comment by truongngoclinh** [comment]
@dmitrikudrenko actually was stuck with building jar file, follow the instruction in [official site](http://selendroid.io/architecture.html)
When I run `mvn package`, it somehow cant fetch repos of:
 - [WARNING] The POM for android.support.test:runner:jar:0.5 is missing, no dependency information available
- [WARNING] The POM for android.support.test:exposed-instrumentation-api:aar:0.5 is missing, no dependency information available
- [WARNING] The POM for org.apache.cordova:cordova:jar:android:3.7.0 is missing, no dependency information available
- [WARNING] The POM for org.apache.cordova-android:cordova:jar:android:4.0.0 is missing, no dependency information available
- [WARNING] The POM for com.google.android:support-v4:jar:21.0.3 is missing, no dependency information available

Then failed to build:
selendroid-server .................................. FAILURE

**Comment by marcelogomez** [comment]
This would break for older installations. I believe #1136, fixes it in a backwards compatible way. I'm waiting for the author to  rebase before we can merge it

**Comment by lpetre** [comment]
This was fixed in #1136

**Pull request closed without merging**
