### PR TITLE
Enabled Selendroid to access the UiAutomation APIs

### PR DESCRIPTION
**Pull request by marcelogomez**
[UiAutomation](https://developer.android.com/reference/android/app/UiAutomation.html) is a low level API that allow us to inject events across package boundaries using the system's accessibility APIs. As of API level 18, an instance of it can be obtained via [Instrumentation.getUiAutomation](https://developer.android.com/reference/android/app/Instrumentation.html#getUiAutomation()), however, this method will fail unless the instrument command is run with the -w flag and it is called from a test thread.

This pull request refactors ServerInstrumentation to extend [AndroidJUnitRunner](https://developer.android.com/reference/android/support/test/runner/AndroidJUnitRunner.html) and moves the call to start the http server to ServerManager, a dummy test

### CODE REVIEW

**Comment by marcelogomez** [comment]
This would also take care of #1013

**Comment by DominikDary** [comment]
Hi @marcelogomez,
thanks for the PR! The build is failing. Can you please have a look?

**Comment by marcelogomez** [comment]
Hi @DominikDary !
I'm not sure the issue is related to my changes, it's a dependency conflict with hamcrest. From the logs:
> :selendroid-server:prepareDebugUnitTestDependenciesConflict with dependency 'org.hamcrest:hamcrest-core'. Resolved versions for app (1.3) and test app (1.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by marcelogomez** [comment]
Making the test app explicitly depend on JUnit again which in turn depends on Hamcrest fixed it

**Comment by DominikDary** [comment]
I will have a look next weekend.

**Comment by DominikDary** [comment]
cc @asm89 

@marcelogomez This pull request looks very similar to #1072. Is this one obsolete with the other one or do they need to be merged in a specific order?

**Comment by marcelogomez** [comment]
Yup, this is obsolete now

**Pull request closed without merging**
