### PR TITLE
Fixing support for cordova 3.7.0 apps.

### PR DESCRIPTION
**Pull request by DominikDary**
The issue with this solution is that we need to add the cordova android lib to the local mvn repo in order to build it. The dependency does not need to be added to the selendroid-server, because it is already part of the app under test.

To create a new cordova app:

     cordova create cordovasample
     cd cordovasample
     cordova platform install android
     cordova build     

The built selendroid standalone can be downloaded [here](https://www.dropbox.com/s/261jxklqqhnee9j/selendroid-standalone-0.14.0-SNAPSHOT-with-dependencies.jar?dl=0) to test it.

### CODE REVIEW

**Comment by kruchx** [comment]
Hi Dominik,

I checked you JAR file and now I'm able to run my tests on new Cordova. Thank you very much!

**Comment by smiklosovic** [comment]
@DominikDary  could you merge to master please? We need this really badly.

**Comment by smiklosovic** [comment]
@DominikDary additionally, do not you want to slice a new version? I know it is just few commits after 0.13.0 but this change is so profound and has such impact that using snapshots is PITA.

Thanks for awesome job.

**Comment by DominikDary** [comment]
@smiklosovic so the fix works fine for you, right?

**Comment by DominikDary** [comment]
@jlipps when you try to build master on a different machine, please make sure you have executed this script before:
https://github.com/selendroid/selendroid/blob/master/third-party/cordova-3.7.0/mvnInstall.sh
Cheers

Dominik

PS: You find as well the jars in maven central: Release 0.14.0

**Comment by smiklosovic** [comment]
I have not tried that yet, i have not had time for it. But I know that I hit this issue before, I need to test some Cordova stuff again and I hesitate to do so because I know it does not work. A guy above my reported it works so ... I'll try it tomorrow and get you know.

**Comment by smiklosovic** [comment]
yay! already out ~_~

**Comment by afalko** [comment]
I just tried it with 0.14 as well as 0.15.0-SNAPSHOT and I'm still getting the ClassCastException. I'm on cordova 4.2.0, fwiw. Do I need to downgrade to cordova 3.7?

**Comment by tedlyons** [comment]
Dominik, what released version of Selenium would this be in? I've never built selenium and would hope to just be able to use a released version.  Thanks in advance.

**Comment by lukeis** [comment]
@tedlyons Selenium? huh?   This is in Selendroid 0.14 (and 0.15 has also been released).

**Comment by tedlyons** [comment]
Sorry Luke, where is the selendroid.jar?  I'm using selenium and appium for mobile automation testing.  I want to replace 14 with 15, but can't find it

**Comment by lukeis** [comment]
@tedlyons you'll need to talk to the appium devs about it, to see what version of selendroid is bundled in it, but they usually have the latest.

**Comment by jlipps** [comment]
I think we have selendroid 0.15 in master already, though it's not part of a published version  yet.

**Comment by hardik-d** [comment]
@jlipps @lukeis who is supporting hybrid app support? I am on cordova 5.0 now and seeing similar issue. i have logged multiple bugs but no response. I am stuck for almost a month now, can someone help here please.

**Pull request merged**
