### PR TITLE
append error details to page source

### PR DESCRIPTION
**Pull request by aluedeke**
Currently its not possible to get details about errors with selendroid. this change just appends the error text to the page source.

### CODE REVIEW

**Comment by lukeis** [comment]
looks good for a code perspective.  But can you fix all the formatting differences? Selendroid uses 2 spaces for indentation and 4 spaces for long code line wraps

**Comment by aluedeke** [comment]
@lukeis updated the formatting

**Comment by DominikDary** [comment]
@aluedeke thanks for the update!

Can you please sign the [CLA](http://goo.gl/pAvxEI)? That is needed in order to merge your code in.

Thanks for your contribution!

**Comment by aluedeke** [comment]
@DominikDary signed

**Comment by DominikDary** [comment]
:+1:

**Pull request merged**
