### PR TITLE
Test Coverage for CallLogUtil and HttpClientUtil

### PR DESCRIPTION
**Pull request by danielrobertson**
@mmccartney could you please code review these unit tests I have added for CallLogUtil and HttpClientUtil?

@lukeis or @DominikDary could you please review and merge?

### CODE REVIEW

**Comment by danielrobertson** [comment]
I don't know why the Travis CI build has failed. @lukeis or @DominikDary do you have a suggestion on what I should do to make the build pass? I developed the tests in IntelliJ and did not make additions to the pom.xml

**Comment by lukeis** [comment]
lgtm, can you sign the cla?
http://goo.gl/pAvxEI

**Comment by danielrobertson** [comment]
Oops, thought I had signed previously. I've signed the cla now.

**Comment by mmccartney** [comment]
LGTM

**Pull request merged**
