### PR TITLE
add cordova-android 4.0.0 support

### PR DESCRIPTION
**Pull request by Okanim**
Adding support for the lastest version of cordova-android.

### CODE REVIEW

**Comment by lukeis** [comment]
the build fails because you didn't make the mvnInstall.sh executable, please correct the file permissions

**Comment by DominikDary** [comment]
otherwise :+1: and thanks for signing the CLA!

**Comment by Okanim** [comment]
File permissions done :smile: .

**Comment by DominikDary** [comment]
and thanks @Okanim for your contribution!

**Comment by pavrda** [comment]
Please can you point me what I'm doing wrong. I tried Cordova Android version 3.7, 4.0, 4.1, Selendroid 16 and 17, real device and emulator API version 16,19,21  and everytime crashed on line
```
driver.switchTo().window("WEBVIEW_0");
```
in Android system log I get following:
```
io.selendroid.server.model.SelendroidWebDriver$4#run:399 - Error configuring web view
java.lang.ClassCastException: io.selendroid.server.model.SelendroidWebDriver$4$1 cannot be cast to org.apache.cordova.engine.SystemWebViewClient
at org.apache.cordova.engine.SystemWebView.setWebViewClient(SystemWebView.java:70)
at io.selendroid.server.model.SelendroidWebDriver$4.run(SelendroidWebDriver.java:361)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4745)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
```

When I try test employee-directory.apk it's ok. So I probably do something wrong. Can you help me please?

**Pull request merged**
