### PR TITLE
Hardware devices apiTargetType need to default to android

### PR DESCRIPTION
**Pull request by ILikeToNguyen**

### CODE REVIEW

**Comment by mach6** [comment]
:+1: LGTM

**Comment by asm89** [comment]
@ILikeToNguyen @mach6 Why not set the property in the base class to the default value? https://github.com/selendroid/selendroid/blob/932eba6956c52ccf5a5a7cea795f7e09227dead5/selendroid-standalone/src/main/java/io/selendroid/standalone/android/impl/AbstractDevice.java#L66

**Comment by ILikeToNguyen** [comment]
@asm89 You're right I could have also set the default value at variable declaration in the base class.

**Comment by asm89** [comment]
@ILikeToNguyen Can you send a PR to fix that?

**Pull request merged**
